spring:
    application.name: travelbuddy
    datasource:
        url: jdbc:postgresql://31.223.91.108:5432/travelbuddy
        username: postgres
        password: 'G.Noodle.314*'
        driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect